Squashed commit of the following:
commit 2605e4c04431cd2663ffe453a18b27b974eac7af
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Thu Feb 10 09:00:57 2022 +0100

    Added SENAITE maintenance scripts (#1933)

    * Added senaite scripts runtime and first script

    * Added upgrade script

    * Added reindex script

    * Changelog updated

    * Always upgrade the latest versions

    * Fixed import

commit 27353add97976e2f02a724ff6c11fc8ce7f792c4
Author: Jordi Puiggené <jp@naralabs.com>
Date:   Wed Feb 9 20:57:58 2022 +0100

    Fix cannot attach documents to individual analyses in Worksheet context (#1932)

    * Fix cannot set attachments to specific analyses in Worksheet

    * Remove unnecessary code

    * Changelog

commit 269f1b15a845bc2253899da3056993d71d2c41bd
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Mon Feb 7 12:49:21 2022 +0100

    Ensure valid timezone in DX datetime field setter (#1930)

    * Ensure valid timezone in field setter

    * Changelog updated

    * Convert GMT timezones to Etc/GMT pytz timezones

    * Whitespace only

    * Date API takes care of DateTime conversion

    * Better Timezone conversion

    * Added a note regarding the Etc/GMT Timezone

    * Leverate datetime API for field conversions

    * Check for None type

    * Make Etc/GMT the default fallback

commit 8092b0d84085e9bd2231c4976897e6730acad869
Author: Jordi Puiggené <jp@naralabs.com>
Date:   Mon Jan 31 10:53:57 2022 +0100

    Analysis attachment is copied on retest (#1927)

    * Skip "Attachment" field on analysis' field values copy

    * Changelog

    Co-authored-by: Ramon Bartl <rb@ridingbytes.com>

commit 01df928f715b4fcb58f4edd08137c254f2752bf6
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Mon Jan 31 10:44:56 2022 +0100

    Added `on_change` hook for methods in analyses listings (#1928)

    * Added on_change handler for Methods

    * Changelog updated

    * Enable _on_change_method on worksheet's results entry view

    Co-authored-by: Jordi Puiggené <jp@naralabs.com>

commit 88d3053e635782a60e206d8b2b99dc00649a65ce
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Thu Jan 27 08:38:22 2022 +0100

    Updated Translations from Transifex (#1926)

    * updated translations

    * fixed i18n errors

commit 720033379fa0e348b2879bac663fb4f4c9bc9ebf
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Wed Jan 26 11:23:11 2022 +0100

    Fix sample transition in listings (#1925)

    * Don't set sample date if already set

    * Convert field getter names back to field name

    * Imports only

    * Fixed datetime conversion in sample listing when sample wf is active

    * Fixed workflow adapter for sample transition in listings

    * Changelog updated

    * Allow to set min/max values for datetime field

commit b0506d8d5f7fdd686f150eab82ded03ac1e9e9c4
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Tue Jan 25 17:08:51 2022 +0100

    Fix viewlet rendering error on login screen (#1924)

    * Hide socialtags viewlets

    * Update CHANGES.rst

    * Update CHANGES.rst

    Co-authored-by: Jordi Puiggené <jp@naralabs.com>

commit a030d92b8ca02907a660582a85a05dfa030e9b86
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Tue Jan 25 17:04:35 2022 +0100

    Use native date input fields in reports (#1923)

    * Use native date input fields in reports

    * Changelog updated

    Co-authored-by: Jordi Puiggené <jp@naralabs.com>

commit 61fb6f339a225581986c0728ea9462f279897bdb
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Mon Jan 24 12:14:58 2022 +0100

    Fix indexed attributes not set when adding a new index with catalog API (#1920)

    * Fixed catalog API indexed attributes not set when adding a new index

    * Changelog updated

commit 0e81ba7d555a0811ee4d88df2db89fcfcdf014ae
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Fri Jan 21 17:14:03 2022 +0100

    Always call object info adapter with a record (#1919)

commit 28a3169e401c494ba9fd755f1c95061e3eec7ab1
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Fri Jan 21 17:11:15 2022 +0100

    Fix stale combobox items displayed when search query changed (#1918)

    * Force combobox close when search query changed

    * Remove portal_factory check in combobox JS

    * Handle portal_factory urls

    * Generated coffee script

    * Changelog updated

commit 314f80b4333098aa3f3c0efdbdda8ab10c868ac4
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Fri Jan 21 12:01:18 2022 +0100

    Fix wrong context in reference widget lookups (#1917)

    * Use absolute context url for reference widget lookups

    * Changelog updated

commit 8a1f37cec27b9a7c6b5b6592fb70072927b49065
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Fri Jan 21 10:32:46 2022 +0100

    Provide the request record to object info adapters in the sample add form (#1916)

    * Provide the request record to object info adapters

    * Changelog

    * Removed argument for base method

commit 6cb368fa6a2353bc5a66c66a99714a0f1f3a2fc4
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Thu Jan 20 15:17:04 2022 +0100

    Ported PR #1865 for dexterity contents (#1913)

    * Ported PR #1865 for dexterity contents

    * Changelog updated

    Co-authored-by: Jordi Puiggené <jp@naralabs.com>

commit f15e188cdc4bb2bdd0372f221c0d5f1f454e76b9
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Thu Jan 20 15:14:13 2022 +0100

    Support list queries in dx reference widget (#1915)

    * Build production JS

    * Support lists for catalog queries in DX reference widget

    * Changelog updated

    Co-authored-by: Jordi Puiggené <jp@naralabs.com>

commit cb77fc30319fc68baf11c595bb73069ce00c488b
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Thu Jan 20 15:11:34 2022 +0100

    Provide context, widget and fieldname for callable base queries in AT reference widgets (#1914)

    * Call base query callable with context, widget and fieldname

    * Changelog updated

    * Return the dereferenced base query

commit b077f7ef12d7b24ebf8db852a9b54ce69aa86c62
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Wed Jan 19 13:47:46 2022 +0100

    Fixed typo in sample view (#1912)

    * Fixed typo

    * Changelog updated

commit 6c5fa8ad7fcb5373718c00db780e68ee98d823a7
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Mon Jan 17 12:07:47 2022 +0100

    Avoid parse errors for ZCTextIndex (#1910)

    Traceback (innermost last):
      Module ZServer.ZPublisher.Publish, line 144, in publish
      Module ZPublisher.mapply, line 85, in mapply
      Module ZServer.ZPublisher.Publish, line 44, in call_object
      Module senaite.app.listing.view, line 216, in __call__
      Module senaite.app.listing.ajax, line 109, in handle_subpath
      Module senaite.core.decorators, line 20, in decorator
      Module senaite.app.listing.decorators, line 63, in wrapper
      Module senaite.app.listing.decorators, line 50, in wrapper
      Module senaite.app.listing.decorators, line 100, in wrapper
      Module senaite.app.listing.ajax, line 432, in ajax_folderitems
      Module senaite.app.listing.decorators, line 88, in wrapper
      Module senaite.app.listing.ajax, line 313, in get_folderitems
      Module senaite.app.listing.view, line 901, in folderitems
      Module senaite.app.listing.view, line 715, in _fetch_brains
      Module senaite.app.listing.view, line 781, in search
      Module senaite.app.listing.view, line 708, in text_index_search
      Module Products.CMFPlone.CatalogTool, line 463, in searchResults
      Module Products.ZCatalog.ZCatalog, line 625, in searchResults
      Module Products.ZCatalog.Catalog, line 1091, in searchResults
      Module Products.ZCatalog.Catalog, line 634, in search
      Module Products.ZCatalog.Catalog, line 564, in _search_index
      Module Products.ZCTextIndex.ZCTextIndex, line 209, in query_index
      Module Products.ZCTextIndex.QueryParser, line 153, in parseQuery
      Module Products.ZCTextIndex.QueryParser, line 193, in _parseOrExpr
      Module Products.ZCTextIndex.QueryParser, line 211, in _parseAndExpr
      Module Products.ZCTextIndex.QueryParser, line 233, in _parseNotExpr
      Module Products.ZCTextIndex.QueryParser, line 241, in _parseTerm
      Module Products.ZCTextIndex.QueryParser, line 260, in _parseAtom
      Module Products.ZCTextIndex.QueryParser, line 188, in _get
      Module Products.ZCTextIndex.QueryParser, line 174, in _require
    ParseError: Token <Token:ATOM> required, u'OR' found

commit 617311115f6dbb5cd1fd348e238a70c5c247cfe6
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Sun Jan 16 12:41:22 2022 +0100

    Allow to navigate and select with arrow keys in dexterity reference widget  (#1909)

    * Fixed results highlighting

    * Allow to navigate and select results with arrow keys

    * Changelog updated

    * Allow to navigate pages with left/right keys

    * Search on keydown and clear on backspace

    Co-authored-by: Jordi Puiggené <jp@naralabs.com>

commit 1f22fecfb4504156d3d7487c440a6382a2aeda45
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Sun Jan 16 12:39:28 2022 +0100

    Added searchable text querystring converter to catalog API (#1908)

    * Added searchable text querystring converter to catalog API

    * Changelog updated

    Co-authored-by: Jordi Puiggené <jp@naralabs.com>

commit cd037c69f46da8b42cd9305ed0410f1b61bf8517
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Sun Jan 16 12:20:31 2022 +0100

    Fix datetime field/widget shows current date and time if empty (#1907)

    * Fix datetime widget shows current date if empty

    This also happened for older `datetime.date` objects in the DB

    * Changelog updated

    * Support date strings in date API

    * Raise API Error instead

commit 14eff7b51c0003443216edb564df0b32430bcbc5
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Sat Jan 15 20:14:12 2022 +0100

    Revert "Check for a date value in widget"

    This reverts commit 97b18cbd916958e03c49cbbec6befa709717b975.

commit be3d500ee4f6c6282274cd0b5d0041d1e6275545
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Sat Jan 15 10:07:34 2022 +0100

    Revert "Support date strings in date API"

    This reverts commit 708a051a505b12893c318eb3aec9d693bbfcfb1d.

commit b10395bac827fa7e2205f796a61d2c83ad5f60b7
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Sat Jan 15 10:07:11 2022 +0100

    Revert "Revert "Fix empty field in sample add form when using edit accessor (#1905)""

    This reverts commit 9f654adc1841b3be64a09a0b9f3f2ff136fd082f.

commit 9f654adc1841b3be64a09a0b9f3f2ff136fd082f
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Sat Jan 15 10:04:27 2022 +0100

    Revert "Fix empty field in sample add form when using edit accessor (#1905)"

    This reverts commit b1f81261354afa0b227ea7f355d561733a743fd5.

commit 97b18cbd916958e03c49cbbec6befa709717b975
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Sat Jan 15 09:56:55 2022 +0100

    Check for a date value in widget

commit 708a051a505b12893c318eb3aec9d693bbfcfb1d
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Sat Jan 15 09:56:13 2022 +0100

    Support date strings in date API

commit b1f81261354afa0b227ea7f355d561733a743fd5
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Thu Jan 13 13:27:17 2022 +0100

    Fix empty field in sample add form when using edit accessor (#1905)

    * Fix empty field in sample add form when using edit accessor

    * Changelog updated

    * Fixed buildout version

commit c96fa990062ffc40c02d6afe591a2cba6bf88116
Author: Jordi Puiggené <jp@naralabs.com>
Date:   Wed Jan 5 11:21:06 2022 +0100

    Update release notes

commit b5681b4004ecb94317c698c733b69464626b3dd8
Author: Jordi Puiggené <jp@naralabs.com>
Date:   Wed Jan 5 11:14:55 2022 +0100

    Version bump v2.2.0

commit 862acfd7186fce9213f34a85ea4165cf9385a126
Merge: 84f108905 80a16ab67
Author: Jordi Puiggené <jp@naralabs.com>
Date:   Wed Jan 5 11:04:25 2022 +0100

    Release 2.1.0 (220105)

commit 80a16ab67bf7c36a971fe222906a06322c685ca6
Author: Jordi Puiggené <jp@naralabs.com>
Date:   Wed Jan 5 11:03:18 2022 +0100

    Update translations

commit c848b04da012a722793b4faee22845694fec98cb
Author: Jordi Puiggené <jp@naralabs.com>
Date:   Wed Jan 5 10:51:55 2022 +0100

    Added translators

commit abff9e63e544041845cd3fb38b7d9332effb6bc8
Author: Jordi Puiggené <jp@naralabs.com>
Date:   Wed Jan 5 10:17:54 2022 +0100

    Fix NestingError

commit 8fbea9458d4c91f692d967e7c052192cf1d3f953
Author: Jordi Puiggené <jp@naralabs.com>
Date:   Wed Jan 5 10:05:15 2022 +0100

    Update contributors

commit 5ddb91e2a77bda413785209221ad3c2cd4d43108
Author: Jordi Puiggené <jp@naralabs.com>
Date:   Wed Jan 5 09:45:51 2022 +0100

    Version change 2.0.1 --> 2.1.0

commit 84f108905c59088d3c45ddc5fb1cc21d94aaa60c
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Tue Jan 4 19:18:04 2022 +0100

    Added date and time field/widget for Dexterity contents (#1903)

    * Implemented datetime field

    * Custom setter for datetime field

    * Implemented datetime widget

    * Handle timezones

    * Added datetime API

    * Always localize the date on field level

    * Datetime widget refactored to use the date API

    * Extended API

    * Check if timezone is callable

    This can be the case when the `default_timezone` is set through
    a directive on the widget, e.g.:

      from plone.app.event.base import default_timezone

    * Changelog updated

    * Updated scrutinizer config

    * Added API function to generate a POSIX timestamp

    * Added from_timestamp API function

    * Added ISO format API

    * Handle Python date objects

    * Dropped get_min/get_max methods

    * Test fixed for TZ

    * Fixed datetimewidget display value

    * Test fixture

    * Fixed test

commit 2d6cc3503c3c751785e80d407993011e7d218ec5
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Mon Jan 3 16:57:19 2022 +0100

    Allow date fields to be unset (#1904)

commit 985b8f1918b45da4a17be929739b8df4427236c0
Author: toropok <leonid.toporkov@gmail.com>
Date:   Mon Jan 3 21:22:32 2022 +0700

    Fix DurationValidator when field value is empty (#1890)

    * Update DurationValidator

    * Update CHANGES.rst

commit 8779528c17689c52d2c5d6d357449d45d117afe4
Author: Jordi Puiggené <jp@naralabs.com>
Date:   Thu Dec 23 15:38:41 2021 +0100

    Ensure `get_tool` returns a tool when a name is set as the default param (#1902)

    * Ensure get_tool's default returns a tool

    * Added doctest

commit 13498f3226aed2ec8cca43d4eac229cbc9f1cc4f
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Mon Dec 20 15:15:30 2021 +0100

    Fix snapshot listing fails on orphan catalog entries (#1900)

    * Fix snapshot listing fails on orphan catalog entries

    * Changelog updated

commit c219b2283dc76d4bc7dc23c91e1feb50a219dfa9
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Mon Dec 20 15:14:05 2021 +0100

    Improved style for datetimewidget w/o hard coded width (#1901)

    This fixes a side effect in the results table view

commit 0755ba741552b277291a2d8a2c98ea3c375dfa42
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Wed Dec 15 12:09:15 2021 +0100

    Fix archetype tool catalog mappings (#1898)

    * Fix archetype tool catalog mappings

    * Comment added

commit 4eb6c68b63420bc206d277dde75562b73e7b9739
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Tue Dec 14 09:45:22 2021 +0100

    Support date and number fields copy in sample add form (#1897)

    * Copy date/time/hidden fields

    * Changelog

commit 6256c3864eea9d6d740c2b678255c20ef6bc9aef
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Mon Dec 13 10:35:15 2021 +0100

    Custom date and time widget (#1896)

    * Always show time if long_format is requested

    * Imports sorted

    * Changed datetimewidget properties in instrumentcertification

    * Fixed TZ offset issue in "valid to" instrument certification field

    * Updated datetimewidget to display date and time separate

    * Hide time input if show_only is false

    * Added JS docstrings

    * Changelog updated

    * Avoid time cropping in FireFox

    * Make form controls 260px wide

    * Conditional widths

commit 15dd407028b062d902d1573abf06b966d4a08991
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Thu Dec 9 16:49:13 2021 +0100

    Disable native form validation in header table (#1895)

    * No native form validation in header table

    * Changelog updated

commit 91b4bc0dceb10ff44a8c0ef3c27a2aaba68ede88
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Wed Dec 8 17:40:44 2021 +0100

    Removed unused field PasswordLifeTime (#1893)

    * Removed blind field PasswordLifeTime

    * Changelog updated

commit 6cbbfb474f57f49c278315fa08bed1b2c5d4d6cf
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Wed Dec 8 12:21:26 2021 +0100

    Drop jQuery Datepicker for HTML5 native date fields (#1892)

    * Removed jQuery timepicker JS

    * removed jquery timepicker from webpack config

    * rebuild production js

    * removed datetime js from site

    * Use HTML date or datetime-local input field

    * Added copy functionality in add form for date fields

    * Return ISO8601 format

    * Changelog updated

    * Removed

    * Use manual formatted date format for min/max

    * datetime-local field requires local date format w/o timezone

    * Use correct datetime field

    * Removed malicious DateTime field in bika namespace

    * Comment only